package controle;

/* @author SKIIW */

public class formulario extends javax.swing.JFrame
{
    public formulario()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnMultiplicar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visorCalculadora = new javax.swing.JTextPane();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnSubtrair = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnSomar = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMultiplicar.setBackground(new java.awt.Color(0, 255, 255));
        btnMultiplicar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnMultiplicar.setForeground(new java.awt.Color(0, 102, 102));
        btnMultiplicar.setText("*");
        btnMultiplicar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnMultiplicarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        visorCalculadora.setBackground(new java.awt.Color(204, 255, 255));
        visorCalculadora.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        visorCalculadora.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(visorCalculadora);

        btn1.setBackground(new java.awt.Color(0, 255, 255));
        btn1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(0, 102, 102));
        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn1MouseClicked(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 255, 255));
        btn2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(0, 102, 102));
        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn2MouseClicked(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 255, 255));
        btn4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(0, 102, 102));
        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn4MouseClicked(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 255, 255));
        btn5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(0, 102, 102));
        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn5MouseClicked(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 255, 255));
        btn7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(0, 102, 102));
        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn7MouseClicked(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn7ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 255, 255));
        btn9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(0, 102, 102));
        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn9MouseClicked(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 255, 255));
        btn8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(0, 102, 102));
        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn8MouseClicked(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 255, 255));
        btn3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(0, 102, 102));
        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn3MouseClicked(evt);
            }
        });

        btnCE.setBackground(new java.awt.Color(0, 255, 255));
        btnCE.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnCE.setForeground(new java.awt.Color(0, 102, 102));
        btnCE.setText("CE");
        btnCE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCEMouseClicked(evt);
            }
        });
        btnCE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCEActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(0, 255, 255));
        btnIgual.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(0, 102, 102));
        btnIgual.setText("=");
        btnIgual.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnIgualMouseClicked(evt);
            }
        });
        btnIgual.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIgualActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(0, 255, 255));
        btn0.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn0.setForeground(new java.awt.Color(0, 102, 102));
        btn0.setText("0");
        btn0.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn0MouseClicked(evt);
            }
        });

        btnSubtrair.setBackground(new java.awt.Color(0, 255, 255));
        btnSubtrair.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSubtrair.setForeground(new java.awt.Color(0, 102, 102));
        btnSubtrair.setText("-");
        btnSubtrair.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnSubtrairMouseClicked(evt);
            }
        });

        btnDividir.setBackground(new java.awt.Color(0, 255, 255));
        btnDividir.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnDividir.setForeground(new java.awt.Color(0, 102, 102));
        btnDividir.setText("/");
        btnDividir.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnDividirMouseClicked(evt);
            }
        });

        btnSomar.setBackground(new java.awt.Color(0, 255, 255));
        btnSomar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSomar.setForeground(new java.awt.Color(0, 102, 102));
        btnSomar.setText("+");
        btnSomar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnSomarMouseClicked(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 255, 255));
        btn6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(0, 102, 102));
        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultiplicarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnMultiplicarMouseClicked
    {//GEN-HEADEREND:event_btnMultiplicarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplicarMouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn1MouseClicked
    {//GEN-HEADEREND:event_btn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn2MouseClicked
    {//GEN-HEADEREND:event_btn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn4MouseClicked
    {//GEN-HEADEREND:event_btn4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn6MouseClicked
    {//GEN-HEADEREND:event_btn6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn5MouseClicked
    {//GEN-HEADEREND:event_btn5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn7MouseClicked
    {//GEN-HEADEREND:event_btn7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn9MouseClicked
    {//GEN-HEADEREND:event_btn9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn8MouseClicked
    {//GEN-HEADEREND:event_btn8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn3MouseClicked
    {//GEN-HEADEREND:event_btn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseClicked

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn2ActionPerformed
    {//GEN-HEADEREND:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnCEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCEMouseClicked
    {//GEN-HEADEREND:event_btnCEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCEMouseClicked

    private void btnIgualMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnIgualMouseClicked
    {//GEN-HEADEREND:event_btnIgualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualMouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn0MouseClicked
    {//GEN-HEADEREND:event_btn0MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0MouseClicked

    private void btnSubtrairMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSubtrairMouseClicked
    {//GEN-HEADEREND:event_btnSubtrairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubtrairMouseClicked

    private void btnDividirMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnDividirMouseClicked
    {//GEN-HEADEREND:event_btnDividirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDividirMouseClicked

    private void btnSomarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSomarMouseClicked
    {//GEN-HEADEREND:event_btnSomarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSomarMouseClicked

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCEActionPerformed
    {//GEN-HEADEREND:event_btnCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIgualActionPerformed
    {//GEN-HEADEREND:event_btnIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn7ActionPerformed
    {//GEN-HEADEREND:event_btn7ActionPerformed
        String valor = visorCalculador.getText();
    visorCalculador.setText(valor + "7"); 
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn9ActionPerformed
    {//GEN-HEADEREND:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public
                    void run()
            {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane visorCalculadora;
    // End of variables declaration//GEN-END:variables
}
